apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
  labels:
    app: forgejo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: forgejo
  name: forgejo-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-configmap
  namespace: forgejo
  labels:
    app: forgejo
data:
  USER_UID: "1000"
  USER_GID: "1000"
  FORGEJO__database__DB_TYPE: "postgres"
  FORGEJO__database__HOST: "10.0.0.9"
  FORGEJO__database__NAME: "forgejo"
  FORGEJO__database__USER: "forgejo"
  FORGEJO__server__ROOT_URL: "http://jill/forgejo/"
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-service
  namespace: forgejo
spec:
  type: NodePort
  selector:
    app: forgejo
  ports:
    - name: "http"
      nodePort: 31170
      port: 3000
      targetPort: 3000
    - name: "ssh"
      nodePort: 31160
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:14
          envFrom:
            - configMapRef:
                name: forgejo-configmap
            - secretRef:
                name: forgejo-secrets
          ports:
          - containerPort: 3000
            name: http
          - containerPort: 22
            name: ssh
          volumeMounts:
          - name: forgejo-data
            mountPath: /data
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: forgejo-data
          persistentVolumeClaim:
            claimName: forgejo-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
      resources:
        limits:
          memory: "2Gi"
          cpu: "2"
        requests:
          memory: "512Mi"
          cpu: "500m"

