apiVersion: v1
kind: Namespace
metadata:
  name: freshrss
  labels:
    app: freshrss
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-data-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-extensions-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss-deployment
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers: 
      - name: freshrss
        image: freshrss/freshrss:1-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
        - name: CRON_MIN
          valueFrom:
              configMapKeyRef:
                name: freshrss-configmap
                key: CRON_MIN
        volumeMounts:
        - name: freshrss-data
          mountPath: /var/www/FreshRSS/data
        - name: freshrss-extensions
          mountPath: /var/www/FreshRSS/extensions
      volumes:
      - name: freshrss-data
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
      - name: freshrss-extensions
        persistentVolumeClaim:
          claimName: freshrss-extensions-pvc
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "100m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freshrss-configmap
  namespace: freshrss
  labels:
    app: freshrss
data:
  CRON_MIN: "5,20,35,50"
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
  namespace: freshrss
spec:
  type: NodePort
  selector:
    app: freshrss
  ports:
    - nodePort: 31180
      port: 80
      targetPort: 80

