apiVersion: v1
kind: Namespace
metadata:
  name: mssql
  labels:
    app: mssql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mssql
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: mssql-configmap
                  key: mssql-pid
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: mssql-configmap
                  key: accept-eula
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: mssql-sa-password
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "4Gi"
          cpu: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mssql
  name: mssql-pvc
spec:
  storageClassName: homelab
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 25Gi } }
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mssql
  name: mssql-configmap
  labels:
    app: mssql
data:
  mssql-pid: "Developer"
  accept-eula: "Y"
---
apiVersion: v1
kind: Service
metadata:
  namespace: mssql
  name: mssql
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
    - nodePort: 31433
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Secret
metadata:
  namespace: mssql
  name: mssql-secrets
type: Opaque
data:
  mssql-sa-password: eW91clN0cm9uZyghKVBhc3N3b3Jk
