services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: r3d5un:r3d5un
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /opt/jellyfin/config:/config
      - /var/cache/jellyfin:/cache
      - type: bind
        source: /mnt/storage/Videos
        target: /media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://10.0.0.9
    extra_hosts:
      - 'host.docker.internal:host-gateway'
