- name: "Install Docker"
  hosts: "all"
  become: true
  become_method: "sudo"
  tasks:

    - name: "Download Docker GPG apt Key"
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: "Add Docker Repository"
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | lower }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker
        update_cache: true

    - name: "Install system packages"
      ansible.builtin.apt:
        state: present
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: "Create docker group"
      ansible.builtin.group:
        name: docker
        state: present

    - name: "Add user to docker group"
      ansible.builtin.user:
        name: "r3d5un"
        groups: docker
        append: yes

    - name: "Enable Docker service"
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: "Remove dependencies that are no longer required"
      ansible.builtin.apt:
        autoremove: true
        purge: true

