# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

[servers.Libera]
nickname = "r3d5un"
server = "irc.libera.chat"
channels = [
	"#halloy",
	"#ansible",
	"#bash",
	"##chat",
	"#docker",
	"#git",
	"#kde",
	"#kubernetes",
	"#linux",
	"#lobsters",
	"#neovim",
	"#postgresql",
	"##programming",
	"##rust",
	"#ubuntu",
	"#vim",
	"#zig"
]

[buffer.server.messages.topic]
enabled = false

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"
local = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

